config/routes.rb
Rails.application.routes.draw do

  root "blog#index"
  resources :blog, as: :blogs
  resources :comments

end

app/models/author.rb
class Author < ActiveRecord::Base

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates :email, presence: true, uniqueness: true, format: /\A[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})\z/

end

app/models/blog.rb
class Blog < ActiveRecord::Base

  validates :body, presence: true
  validates :author, presence: true, numericality: true
  validates :vote_count, numericality: true
  validates :view_count, numericality: true
  validate :author_exists

  after_initialize :set_default_counts

  def html_summary
    if body.length > 200
      return "#{body.gsub(/\n/, "<br />")[0..200]}..."
    else
      return "#{body.gsub(/\n/, "<br />")}"
    end
  end

  private

  def author_exists
    errors.add(:author, "does not exist!") unless Author.exists?(author)
  end

  def set_default_counts
    self.vote_count ||= 0
    self.view_count ||= 0
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :author, presence: true
  validates :email, presence: true, format: /\A[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})\z/
  validates :body, presence: true
  validates :nested, inclusion: { in: [true, false] }
  validates :parent, presence: true
  validate :parent_exists

  def get_nested_comments
    @output = []
    get_nested_comments_helper(id, 1)
  end

  private

  def parent_exists
    if nested
      errors.add(:parent, "does not exist!") unless Comment.exists?(parent)
    else
      errors.add(:parent, "does not exist!") unless Blog.exists?(parent)
    end
  end

  def get_nested_comments_helper(id, indent)
    comments = Comment.all.where(nested: true).where(parent: id)
    unless comments == []
      comments.each do |x|
        @output << x
        get_nested_comments_helper(x.id, indent+1)
      end
    end
    @output
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :find_post, only: [:edit, :show, :update, :destroy]
  before_action :authenticate, only: [:create, :new]

  def index
    @posts = Blog.all.order("created_at DESC")
  end

  def create
    @post = Blog.new blog_params
    @post.author = session[:user_id]
    if @post.save
      redirect_to @post
    else
      redirect_to new_blog_path, notice: post_errors
    end
  end

  def new
    @post = Blog.new
  end

  def edit
  end

  def show
    @author = Author.find(@post.author)
    @post.increment!(:view_count)
    @temp = Comment.all.where(nested: false).where(parent: @post.id)
    @comments = []
    @temp.each do |x|
      @comments << x
      @comments += x.get_nested_comments
    end
    @comment = Comment.new
  end

  def update
    if @post.update(blog_params)
      redirect_to @post
    else
      redirect_to @post, notice: post_errors
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      redirect_to @post, notice: post_errors
    end
  end

  private

  def authenticate
    # URGENT
    # TODO This is just a dummy authentication and will be updated later
    if session[:user_id].nil?
      session[:user_id] = 2
    end
  end

  def find_post
    @post = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit([:title, :body])
  end

  def post_errors
    @post.errors.full_messages.join("; ")
  end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  def create
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/blog/_comment_form.html.erb
<%= form_for @comment do |f| %>
  <table>
    <tr>
      <td>
        <%= f.label "Your Name" %>
      </td>
      <td>
        <%= f.text_field :author %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :email %>
      </td>
      <td>
        <%= f.text_field :email %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label "Comment" %>
      </td>
      <td>
        <%= f.text_area :body %>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= f.submit %>
      </td>
    </tr>
  </table>
<% end %>

app/views/blog/_post_form.html.erb
<%= form_for @post do |f| %>
<%# f.hidden_field(:author) %>
  <table>
    <tr>
      <td>
        <%= f.label :title %>
      </td>
      <td>
        <%= f.text_field :title %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label "Post" %>
      </td>
      <td>
        <%= f.text_area :body %>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= f.submit %>
      </td>
    </tr>
  </table>
<% end %>

app/views/blog/edit.html.erb
<%= render "post_form" %>

app/views/blog/index.html.erb
<% @posts.each do |post| %>

<h3>
  <%= link_to post.title, post %>
</h3>
[<%= link_to "edit", edit_blog_path(post) %>]
[<%= link_to "delete", post, method: :delete, data: {confirm: "Are you sure? Deleting a post cannot be undone."} %>]
<p>
  <%= post.html_summary %>
</p>

<hr>

<% end %>

app/views/blog/new.html.erb
<%= render "post_form" %>

app/views/blog/show.html.erb
<h3>
  <%= @post.title %>
</h3>
<em>
  Written by <%= mail_to @author.email, @author.username %>
</em>
|
<%= @post.view_count %> views
[<%= link_to "edit", edit_blog_path(@post) %>]
[<%= link_to "delete", @post, method: :delete, data: {confirm: "Are you sure? Deleting a post cannot be undone."} %>]
<br />
<br />
<%= @post.body.gsub(/\n/, "<br />") %>
<br />
<br />
<hr>
<%= render "comment_form" %>
<hr>
<% indent_hash = {} %>
<% indent_multiplier = 0 %>
<% @comments.each do |comment| %>
<% if !comment.nested %>
<% indent_multiplier = 0 %>
<% elsif !indent_hash[comment.parent].nil? %>
<% indent_multiplier = indent_hash[comment.parent] %>
<% else %>
<% indent_multiplier += 1 %>
<% indent_hash[comment.parent] = indent_multiplier %>
<% end %>

<div style="margin-left: <%= indent_multiplier * 25 %>px">
<a href="mailto:<%= comment.email %>"><%= comment.author %></a> says:<br />
<%= comment.body.gsub(/\n/, "<br />") %>
</div>

<hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Home", root_path %>
|
<%= link_to "Create New Post", new_blog_path %>

<hr>

<%= "<div style='border: 1px solid red'>#{flash[:notice]}</div>".html_safe if flash[:notice] %>

<%= yield %>

</body>
</html>